/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang.ui.contentassist

import edu.cmu.cs464.p3.modlang.ui.contentassist.AbstractModLangProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ModLangProposalProvider extends AbstractModLangProposalProvider {
}
