/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractModLangValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(edu.cmu.cs464.p3.modlang.modLang.ModLangPackage.eINSTANCE);
		return result;
	}
}
