/**
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang.validation;

import edu.cmu.cs464.p3.modlang.validation.AbstractModLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModLangValidator extends AbstractModLangValidator {
}
