/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModLangUiModule extends edu.cmu.cs464.p3.modlang.ui.AbstractModLangUiModule {
	public ModLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
