/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ModLangUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return edu.cmu.cs464.p3.modlang.ui.internal.ModLangActivator.getInstance().getInjector("edu.cmu.cs464.p3.modlang.ModLang");
	}
	
}
