/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ModLangStandaloneSetup extends ModLangStandaloneSetupGenerated{

	public static void doSetup() {
		new ModLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

