/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModLangRuntimeModule extends edu.cmu.cs464.p3.modlang.AbstractModLangRuntimeModule {

}
