/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.cmu.cs464.p3.modlang.services.ModLangGrammarAccess;

public class ModLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ModLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.cmu.cs464.p3.modlang.parser.antlr.internal.InternalModLangParser createParser(XtextTokenStream stream) {
		return new edu.cmu.cs464.p3.modlang.parser.antlr.internal.InternalModLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ModLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
