/*
 * generated by Xtext
 */
package edu.cmu.cs464.p3.modlang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("edu/cmu/cs464/p3/modlang/parser/antlr/internal/InternalModLang.tokens");
	}
}
